# Generated by Django 5.1.3 on 2024-11-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, upload_to='BookCovers/'),
        ),
    ]
