# Generated by Django 5.1.3 on 2024-11-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='added_on',
        ),
    ]
